### PR TITLE
feat(generator): set required properties to non-nullable

### PR DESCRIPTION
**Pull request by zorji**

### CODE REVIEW

**Comment by Vovanella95** [comment]
Hi @zorji 

Thanks for contribution and for using our generator!

Our idea was to implement Models with not nullable fields only for Responses. So for responses we should generate separate models and ONLY they should contain not nullable fields. If you want to implement nut nullable fields feature - > please follow this way.

**Comment by ElectricCookie** [comment]
I follow the same approach as @zorji in following the spec exactly. 

@zorji  Thanks for providing the first pointers to the changes. I also changed the generateConstructorPropertiesContent function to mark constructor parameters as required if not nullable. I will test this further and contribute changes back.

**Comment by zorji** [comment]
**Update**

The initial implementation is completed. I haven't made any changes to the tests yet. I am running the compiled code in my own project to see if it works as expected.

**Comment by zorji** [comment]
> Hi @zorji
> 
> Thanks for contribution and for using our generator!
> 
> Our idea was to implement Models with not nullable fields only for Responses. So for responses we should generate separate models and ONLY they should contain not nullable fields. If you want to implement nut nullable fields feature - > please follow this way.

@Vovanella95 do you mind provide an example of your swagger so I can ensure the final implementation meet your requirement?

I am not sure what's the best solution as this is the first time I am trying Flutter/Dart. I am thinking to have a new option, when it's enabled/disabled, it will create different type for all object used in a Request and mark them as nullable.

**Comment by Vovanella95** [comment]
Hi @zorji , sure! We should generate response duplicates. For example if we have next

```
@Get(path: '/pet/findByStatus')
  Future<chopper.Response<List<Pet>>> _petFindByStatusGet(
      {@Query('status') required Pet? pet});
```

We have Pet in response and in parameters. So we should generate 2 Pet classes: Pet and Pet$Response. Result will be


```
@Get(path: '/pet/findByStatus')
  Future<chopper.Response<List<Pet>>> _petFindByStatusGet(
      {@Query('status') required Pet? pet});

class Pet // with nullable fields

class Pet$Response with not nullable fields
```

This will be universal solution. Thanks a lot for contributing. I wanted to implement this feature long time ago but can't find time for it

**Comment by jonasanker** [comment]
Great that work is put into aligning this library to the Swagger/OpenApi specification standard when it comes to nullable types. 🙌

This PR seems to create a mapping between the `required` attribute and nullable types.
However to my knowledge the `required` attribute only reflects if the API expects a property to be present in an object, regardless of its value.
A required property can therefore also be nullable.

According to the [OpenApi specification V3](https://swagger.io/docs/specification/data-models/data-types/#null) `null` is declared like
```json
type: integer
nullable: true
```

Would it not be better to align with the OpenApi specification instead of using a _interpretation_ of when something is nullable?

**Comment by zorji** [comment]
> Great that work is put into aligning this library to the Swagger/OpenApi specification standard when it comes to nullable types. 🙌
> 
> This PR seems to create a mapping between the `required` attribute and nullable types. However to my knowledge the `required` attribute only reflects if the API expects a property to be present in an object, regardless of its value. A required property can therefore also be nullable.
> 
> According to the [OpenApi specification V3](https://swagger.io/docs/specification/data-models/data-types/#null) `null` is declared like
> 
> ```json
> type: integer
> nullable: true
> ```
> 
> Would it not be better to align with the OpenApi specification instead of using another _interpretation_ of when something is nullable?

I do agree with you but I am quite new to the Dart land so I need some help here. (I work more in JavaScript/TypeScript)

What would be the right type in Dart to represent the following 2 types?

```
{
 "fieldA": string
  "fieldB": string | null (required = true, nullable = true)
}

{
  "fieldA": string
  "fieldB": string? (required = false, nullable = false)
}
```

I am not sure whether it's possible to represent so I kinda merge nullable and required into one when working with Dart. But if there is a better way, please let me know.

**Comment by Vovanella95** [comment]
Hi @zorji 
I've re-implemented this feature [here](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/370)

I will decline your PR. Anyway thanks for contributing and sorry for long answer.

**Comment by zorji** [comment]
Thanks for the efforts @Vovanella95 
very appreicated

**Pull request closed without merging**
