### PR TITLE
Version/2.4.10

### LINKED ISSUE #384: [BUG] Missing parameter annotations when parsing "$ref" fields
Spotify's [open-api-schema.yml](https://developer.spotify.com/_data/documentation/web-api/reference/open-api-schema.yml) contains reference fields to parameter components. Despite getting parsed correctly and using the type definition of their referenced component, parameters are not annotated correctly in the generated `.swagger.dart` file.

**Generated:**
```dart
///Get Playlist Items
///
///@param
///@param
///@param fields
///@param
///@param
///@param
@Get(path: '/playlists/{playlist_id}/tracks')
Future<chopper.Response<Object>> _playlistsPlaylistIdTracksGet(
    {@Path('playlist_id') required String? playlistId,
    @Query('market') String? market,
    @Query('fields') String? fields,
    @Query('limit') int? limit,
    @Query('offset') int? offset,
    @Query('additional_types') String? additionalTypes});
```

**Source (heavily truncated):**
```yml
/playlists/{playlist_id}/tracks:
  get:
    operationId: get-playlists-tracks
    summary: |
      Get Playlist Items
    description: |
      Get full details of the items of a playlist owned by a Spotify user.
    parameters:
      - $ref: '#/components/parameters/PathPlaylistId'
      - $ref: '#/components/parameters/QueryMarket'
      -
        name: fields
        required: false
        in: query
        schema:
          title: Fields
          description: |
            Filters for the query: a comma-separated list of the
            fields to return. [...]
          type: string
      - $ref: '#/components/parameters/QueryLimit'
      - $ref: '#/components/parameters/QueryOffset'
      - $ref: '#/components/parameters/QueryAdditionalTypes'
    responses:
      "200":
        $ref: "#/components/responses/PagingObject"
      "401":
        $ref: "#/components/responses/Unauthorized"
      "403":
        $ref: "#/components/responses/Forbidden"
      "429":
        $ref: "#/components/responses/TooManyRequests"
    security:
      -
        oauth_2_0:
          - playlist-read-public
          - playlist-read-private

[...]

parameters:
  PathPlaylistId:
    name: playlist_id
    required: true
    in: path
    schema:
      title: Playlist ID
      description: |
        The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) of the playlist.
      example: 3cEYpjA9oz9GiPac4AsH4n
      type: string
  QueryLimit:
      name: limit
      required: false
      in: query
      schema:
        title: Limit
        description: |
          The maximum number of items to return. Default: 20. Minimum: 1. Maximum: 50.
        default: 20
        example: 10
        type: integer
        minimum: 0
        maximum: 50
```

Only the locally defined parameter `fields` appears in the doc comment. Apart from that, there's also an issue regarding parameter descriptions which are completely absent in the generated file. There are no additional options specified in my `build.yaml` besides input and output.

**Library version used:**
`swagger_dart_code_generator 2.4.9`

### PR DESCRIPTION
**Pull request by Vovanella95**
Fix #384

### CODE REVIEW

**Comment by doodlezucc** [comment]
@Vovanella95 When I try to run `dart run build_runner build` with this branch, I get the following log report:
```
[INFO] Generating build script completed, took 413ms
[INFO] Reading cached asset graph completed, took 49ms
[INFO] Checking for updates since last build completed, took 407ms
[WARNING] swagger_dart_code_generator|lib/src/models/swagger_enum.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds. completed, took 7ms
[INFO] Generating build script completed, took 80ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 1.4s
[INFO] Building new asset graph completed, took 633ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] swagger_dart_code_generator:swagger_dart_code_generator on lib/openapi/spotify.yaml:

UnexpectedOutputException: spotify_api|lib/generated/spotify.swagger.dart
Expected only: {spotify_api|lib/generated/client_index.dart, spotify_api|lib/generated/client_mapping.dart}
[INFO] Running build completed, took 8.3s
[INFO] Caching finalized dependency graph completed, took 31ms
[SEVERE] Failed after 8.4s
```

This [SEVERE] error only appears if the `version/2.4.10` branch is selected, everything's fine on `master`. It's because of the 704a94f4a1fe9f41daf7ab93a31c9aa11be0edbd commit, specifically the `_generateExtensions` method. Since refactoring the code, I'm getting two asset ID's: one with forward slashes and one with backslash separators. It doesn't matter what separator I use in my `build.yaml`.

**Before refactor:**
Before commit
**After refactor:**
After commit

**Comment by Vovanella95** [comment]
@doodlezucc  will check your case

**Comment by Vovanella95** [comment]
@doodlezucc are you using generation from urls, or from local files? I refactored caching logic and did not checked all cases yet :)

**Comment by doodlezucc** [comment]
I'm only using a single local file, the project structure looks like this:
```
lib
 - generated (output folder)
 - openapi   (input folder)
   - spotify.yaml
build.yaml
```

**Comment by Vovanella95** [comment]
@doodlezucc sorry for a lot of issues, will handle everything soon

**Comment by Vovanella95** [comment]
Hi @doodlezucc  can you proof issue with `UnexpectedOutputException: spotify_api|lib/generated/spotify.swagger.dart` is still reproduced? I've tried to make project structure like yours - and everything generates well.

**Comment by Vovanella95** [comment]
@doodlezucc  also I've fixed some cases according your changes.

**Comment by doodlezucc** [comment]
@Vovanella95 Hey, I just pulled the latest commits. Unfortunately, the error still persists. :(
If it helps, I'm on Windows, using Dart SDK version 2.15.0. Here's my `build.yaml`:
```yaml
targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/openapi"
          output_folder: "lib/generated/"
```

**Comment by Vovanella95** [comment]
@doodlezucc  will ckeck it on Windows. Thanks for fast answer.

**Comment by doodlezucc** [comment]
I just tried making some changes to the code and found a fix, but I don't know if it's suitable for different cases.
Everything works fine if you replace the backslashes in `filesPaths`, line 65 https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/704a94f4a1fe9f41daf7ab93a31c9aa11be0edbd/lib/swagger_dart_code_generator.dart#L65
by using the following code instead:
```dart
final filesPaths = filesList.map((e) => e.path.replaceAll('\\', '/'));
```

**Comment by Vovanella95** [comment]
@doodlezucc thanks for investigation. It will be helpfull

**Comment by Vovanella95** [comment]
hi @doodlezucc  I've finally found time to check it on my Windows PC. Indeed your fix helps. I will check tommorow morning how it works on mac OS and then we will finally merge this. And I will release new version if everything will be fine. Thanks a lot for collaboration!

**Pull request merged**
