### PR TITLE
Add default values for enums

### PR DESCRIPTION
**Pull request by via-guy**

### CODE REVIEW

**Comment by via-guy** [comment]
Damn, this doesn't work because the generated class from `json_serializable` doesn't add the `enums.` prefix.

**Comment by via-guy** [comment]
@Vovanella95 as I mentioned this doesn't actually work, because the files generated by `json_serializable` can't reference the `as enums` namespace. Trying to find a solution now.

**Comment by Vovanella95** [comment]
@via-guy  ok, waiting for fix. Also, I have issue with generation of some files (Format exception). Will fix this one.

**Comment by via-guy** [comment]
I'm struggling like crazy to solve this issue in `json_serializable`. In `enum_utils.dart` there's the function `enumValueMapFromType`, which creates the enum maps. The problem is that the `Element` value doesn't contain the import prefix, and I don't know how to get it from the `Element`, since it's the parent class that uses the prefix, not the `Element` itself. Could you have a look to see if you can find out how to get it?

**Comment by Vovanella95** [comment]
@via-guy  no, enums prefix has been added to avoid models and enums names conflicts

**Comment by Vovanella95** [comment]
@via-guy I will also take a look into this soon and try to fix it

**Comment by via-guy** [comment]
> @via-guy no, enums prefix has been added to avoid models and enums names conflicts

Is that really a problem? Are API designers creating enums and models with the same name? That sounds like a serious design issue, no? Oh well... 😞

**Comment by via-guy** [comment]
> @via-guy I will also take a look into this soon and try to fix it

Thanks. I spent a very long time trying to see if I could create a fix for `json_serializable` where I could get the import prefix, but it seems like that information is lost along the way in the `build`/`analyzer` flow :(

**Comment by Vovanella95** [comment]
We can pass `fromJson` and `toJson` methods to @JsonKey for enums. It's already should happening for all enum properties. In this case json_serializable knows nothing about enums.

@via-guy

**Comment by via-guy** [comment]
@Vovanella95 the problem is that when you set a default value the generated code needs to use that, so you get something like this:
```dart
validationStatus: json['validation_status'] == null
    ? AddExistingTicketValidationStatus.inProgress
    : addExistingTicketValidationStatusFromJson(
        json['validation_status'])
```
so even though it's using our `fromJson` function, it needs to provide the default value, which means needing the `enums.` prefix.
Another solution would be, instead of using the actual prefix, to pass (in this example)
```dart
validationStatus: json['validation_status'] == null
    ? addExistingTicketValidationStatusFromJson('in_progress')
    : addExistingTicketValidationStatusFromJson(
        json['validation_status'])
```
Let me work on this. It's not an ideal solution, but it should work.

**Comment by Vovanella95** [comment]
@via-guy let's maybe revert your changes, raise and issue, when you describe problem, you tried to solve and I will try to fix it. Share swagger code snippet and expected result.

**Comment by Vovanella95** [comment]
Look like issue is not trivial, it will be better to implement it by me

**Comment by via-guy** [comment]
My alternate solution doesn't work, because it generates:
```dart
@JsonKey(
    name: 'validation_status',
    toJson: addExistingTicketValidationStatusToJson,
    fromJson: addExistingTicketValidationStatusFromJson,
    defaultValue: addExistingTicketValidationStatusFromJson('in_progress'))
```
which fails to compile because `addExistingTicketValidationStatusFromJson('in_progress')` isn't a constant expression.

**Comment by via-guy** [comment]
@Vovanella95 I think you're right, we need to revert my changes.

**Comment by Vovanella95** [comment]
@via-guy  let's raise issue. I will try to take a look into it asap

**Pull request merged**
