### PR TITLE
[feature] Ability to generate mutable models

### PR DESCRIPTION
**Pull request by rockgecko-development**
I needed the ability to generate mutable, non-final models, so I went ahead and added it. 
Offering this PR if you'd like the option as well.

Usage:
new option `models_immutable`, default is `false`. When `true`, the `final` keyword is omitted from model properties.

I also restored (#204 ) the functionality of the `use_path_for_request_names` option, because it wasn't working and I needed it. Default is now `true`. When `false`, the swagger `operationId` is used as the method name (but converted to lowerCamelCase). The path-generated method names looked particularly ugly for me, whereas in my C# Azure Function I have declared the operationId as the same as the Azure Function (& C# method) name, so this lines up perfectly for me. (I'm using this project in the backend: https://github.com/Azure/azure-functions-openapi-extension )

I also added swagger method `description` fields as comments, in addition to the existing `summary`. The `azure-functions-openapi-extension` only seems to generate `description`s.

Finally, I added unit tests for the codegen output with `models_immutable` both true and false.

### CODE REVIEW

**Comment by fryette** [comment]
Why do you need mutable models?
We introduced `copyWith` specially for that case

**Comment by rockgecko-development** [comment]
Yes I'm aware of `copyWith`, certainly I had to update that part of the codegen after removing the search for 'final '.
But that's quite awkward to use if you need to change a single deeply nested field in a parameter of a POST body. This can happen eg if you have a filter API that uses a shared filter model on the frontend and backend (just as an example).

Sure, not recommended for certain situations, quite useful for other situations. A codegen library can give you the option, it doesn't have to dictate. (The `openapi-generator` project using the `dart` generator creates mutable models, the `dart-dio-next` generator creates immutable).

**Comment by rockgecko-development** [comment]
I actually found this project via this thread in the openapi-generator-dart project, and was inspired by this relevant feature request: https://github.com/gibahjoe/openapi-generator-dart/issues/41#issuecomment-882329857
>As nice as immutability is a nice feature, it's a massive pain when passing and manipulating any graph deeper than one level; I think I'm about to cry. The rewriting everything to extract, rebuild, repackage, from all the prior dart generator contracts... it's not only tedious, it's noisy and feels prone to error if the reassignment isn't done in the proper order, etc.

**Comment by Vovanella95** [comment]
Hi @rockgecko-development , It's very good idea to have mutable objects. Unfortunately it contradicts our main idea. Feel free to fork out library and modify it, but we're not going to support mutable models.

**Comment by rockgecko-development** [comment]
What about the other 2 features in this PR?

**Pull request closed without merging**
