### PR TITLE
Added the 'expose_http_client' flag

### PR DESCRIPTION
**Pull request by jeroenvervaeke**
I want to be able to supply a http client to the generated code. This is useful for configuring things like proxies but also for unit testing.

I've added a build option `expose_http_client` that you can add in the `build.yaml`.

With the flag set to `false` (default), the code remains exactly as it was before adding this feature.
When it's enabled the following is generate:
```dart
  static Api create(
      {ChopperClient? client,
      Authenticator? authenticator,
      String? baseUrl,
      Iterable<dynamic>? interceptors,
      http.Client? httpClient}) {
    if (client != null) {
      return _$Api(client);
    }

    final newClient = ChopperClient(
        services: [_$Api()],
        converter: $JsonSerializableConverter(),
        interceptors: interceptors ?? [],
        authenticator: authenticator,
        client: httpClient,
        baseUrl: baseUrl ?? 'http://');
    return _$Api(newClient);
  }
```

The reason why I put this behind a flag is because you need a dependency to `http` when you want to accept `http.Client` as a parameter, which would be a breaking change.

### CODE REVIEW

**Comment by fryette** [comment]
You can create ChopperClient and provide to it custom httpClient with all proxies.
ChopperClient it's simple wrapper.

So my question is why you cannot send configured ChopperClient(with HttpClient inside) instead of HttpClient?

**Comment by jeroenvervaeke** [comment]
> So my question is why you cannot send configured ChopperClient(with HttpClient inside) instead of HttpClient?

To make the library easier to use. Having to create the `ChopperClient` yourself kind of defeats the purpose of having an easy to use automatically generated client.

One could argue the same about `authenticator`, `baseUrl` and the `interceptors`. Why don't drop these arguments and just pass the chopper client there?

```dart
static PetServiceJson create(
      {ChopperClient? client,
      Authenticator? authenticator,
      String? baseUrl,
      Iterable<dynamic>? interceptors}) {
    if (client != null) {
      return _$PetServiceJson(client);
    }

    final newClient = ChopperClient(
        services: [_$PetServiceJson()],
        converter: $JsonSerializableConverter(),
        interceptors: interceptors ?? [],
        authenticator: authenticator,
        baseUrl: baseUrl ?? 'http://petstore.swagger.io/v2');
    return _$PetServiceJson(newClient);
  }
```
source: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/example/lib/swagger_generated_code/pet_service_json.swagger.dart#L23

_Optionally_ adding the `HttpClient` to the `create` factory is consistent with how the other parameters are configured ( `authenticator`, `baseUrl`, `interceptors`).

The way I've added it also makes it entirely optional, so it doesn't cause anything to be backward incompatible.

**Comment by Dumoulin-Lander** [comment]
@Vovanella95 Can you elaborate on how it's possible to expose the `ChopperClient`?

**Comment by Vovanella95** [comment]
Hi @Dumoulin-Lander , you can do this when create service instance:

```dart
  final newClient = ChopperClient(
    converter: $JsonSerializableConverter(),
    //any parameters you want
  );

  final service = PetServiceJson.create(client: newClient);
```

**Comment by Dumoulin-Lander** [comment]
Thanks for the quick response!

I find myself agreeing with Jeroen here I think. The way you're proposing gives you ways to retain a reference to the `ChopperClient` you pass in, but it does not expose the client out from the service instance.

I guess the ship has sailed on this PR, I'll figure something out myself. Thanks again!

**Comment by jeroenvervaeke** [comment]
Feel free to use my forked repository, I'm don't plan on removing it since I'm using this fork in some of my other projects.

**Comment by Dumoulin-Lander** [comment]
> Feel free to use my forked repository, I'm don't plan on removing it since I'm using this fork in some of my other projects.

There's already an[ issue fixed](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/613) in this main repository that is valuable for me, so I'd rather use it so we can get updates when needed.

Also, hi Jeroen :)

**Comment by Vovanella95** [comment]
@Dumoulin-Lander  if it's really important, ok we can merge it :)  I am reopening PR, please ensure CI proccess is succeed

**Comment by Vovanella95** [comment]
@Dumoulin-Lander  please resolve conflicts

**Comment by Vovanella95** [comment]
We can expose ChopperClient without this PR. Closing it.

**Pull request closed without merging**
